In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import embed
from sentence_transformers import SentenceTransformer
import numpy as np
from pathlib import Path
import pandas as pd
import os

In [3]:
data_path = Path("").parent / "data"
combined_clues_path = data_path / "combined_clues"
clues_folder = "2024-05-14-num_games_8934"
n_clues = len(embed.load_clues(clues_folder))
embed.compute_and_save_embeddings(clues_folder, batch_size=32, clues_per_file=50_000)
# os.makedirs(Path(clues_folder) / "embeddings", exist_ok=True)

In [4]:
embeddings_path = combined_clues_path / clues_folder / "embeddings"
embeddings_in_order = sorted(filter(lambda x :x.startswith("embeddings"), os.listdir(embeddings_path)), key=lambda x: int(x.split("_")[1].split(".")[0]))
all_embeddings = np.concatenate([np.load(embeddings_path / f_name) for f_name in embeddings_in_order], axis=0)

In [5]:
# np.savez_compressed(embeddings_path / "all_embeddings.npz", all_embeddings=all_embeddings)
np.save(embeddings_path / "all_embeddings.npy", all_embeddings)

In [23]:
clues = embed.load_clues(clues_folder)

In [24]:
clues

,category,question,response,clue_value,show_number,show_date
20720,ANATOMY,"If the body were a car, they would be the carb...",the lungs,200,1,1983-09-18
20721,ANATOMY,Building these up with steroids has caused spo...,muscles,400,1,1983-09-18
20722,ANATOMY,"Babies have more than 300, while adults have o...",bones,600,1,1983-09-18
20723,ANATOMY,A cranium and 2 femurs on a black flag,a skull and crossbones,800,1,1983-09-18
20724,ANATOMY,This is the body's largest gland,the liver,1000,1,1983-09-18
...,...,...,...,...,...,...
527995,____ FROM THE ____,"A woman who has given birth has gotten this, a...",a visit from the stork,200,9101,2024-05-13
527996,____ FROM THE ____,This rhyming phrase is evoked when someone or ...,a blast from the past,400,9101,2024-05-13
527997,____ FROM THE ____,"This colorful phrase meaning ""unexpected"" invo...",a bolt from the blue,600,9101,2024-05-13
527998,____ FROM THE ____,"Meaning to speak frankly, this saying alludes ...",shoot from the hip,800,9101,2024-05-13
527999,____ FROM THE ____,"To recover from devastating defeat is to ""rise...",Phoenix from the ashes,1000,9101,2024-05-13